<?php

require_once 'villes.php';

$villes = new Villes();

// Une liste de mots, juste pour l'exemple.
// En pratique on chercherait dans une base de données.
$tousLesMots=array('crayon', 'stylo', 'feutre', 'taille-crayon', 'pointe', 'mine', 'gomme', 'dessin', 'coloriage', 'rayure', 'peinture', 'pinceau', 'couleur', 'craie', 'papier', 'feuille', 'cahier', 'carnet', 'carton', 'ciseaux', 'découpage', 'pliage', 'pli', 'colle', 'affaire', 'boîte', 'casier', 'caisse', 'trousse', 'cartable', 'jouet', 'jeu', 'pion', 'dé', 'domino', 'puzzle', 'cube', 'perle', 'chose', 'forme : carré', 'rond', 'pâte à modeler', 'tampon', 'livre', 'histoire', 'bibliothèque', 'image', 'album', 'titre', 'bande dessinée', 'conte', 'dictionnaire', 'magazine', 'catalogue', 'page', 'ligne', 'mot', 'enveloppe', 'étiquette', 'affiche', 'alphabet', 'appareil', 'caméscope', 'cassette', 'cédé', 'cédérom', 'chaîne', 'chanson', 'chiffre', 'contraire', 'différence', 'doigt', 'écran', 'écriture', 'film', 'fois', 'idée', 'instrument', 'intrus', 'lettre', 'liste', 'magnétoscope', 'main', 'micro', 'modèle', 'musique', 'nom', 'nombre', 'orchestre', 'ordinateur', 'photo', 'point', 'poster', 'pouce', 'prénom', 'question', 'radio', 'sens', 'tambour', 'télécommande', 'téléphone', 'télévision', 'trait', 'trompette', 'voix', 'xylophone', 'zéro');

$villes->setVilles(array(

    "NEUILLY" => new Ville("NEUILLY",311),
    "LEVALLOIS" => new Ville("LEVALLOIS",312),
    "CLICHY" => new Ville("CLICHY",313),
    "MONTROUGE" => new Ville("MONTROUGE",321),
    "MALAKOFF" => new Ville("MALAKOFF",322),
    "VANVES" => new Ville("VANVES",323),
    "ISSY LES MOULINEAUX" => new Ville("ISSY LES MOULINEAUX",324),
    "BOULOGNE" => new Ville("BOULOGNE",325),
    "BOIS DE BOULOGNE" => new Ville("BOIS DE BOULOGNE",326),
    "ST OUEN" => new Ville("ST OUEN",331),
    "LA PLAINE ST DENIS" => new Ville("LA PLAINE ST DENIS",332),
    "AUBERVILLIERS" => new Ville("AUBERVILLIERS",333),
    "PANTIN" => new Ville("PANTIN",334),
    "LE PRE ST GERVAIS - LES LILAS" => new Ville("LE PRE ST GERVAIS - LES LILAS",335),
    "BAGNOLET" => new Ville("BAGNOLET",336),
    "MONTREUIL" => new Ville("MONTREUIL",337),
    "VINCENNES" => new Ville("VINCENNES",341),
    "ST MANDE" => new Ville("ST MANDE",342),
    "BOIS DE VINCENNES" => new Ville("BOIS DE VINCENNES",343),
    "CHARENTON ST-MAURICE" => new Ville("CHARENTON ST-MAURICE",344),
    "IVRY" => new Ville("IVRY",345),
    "GENTILLY - LE KREMLIN BICETRE" => new Ville("GENTILLY - LE KREMLIN BICETRE",346),
    "ARCUEIL" => new Ville("ARCUEIL",347),

    "SURESNES" => new Ville("SURESNES",411),
    "PUTEAUX" => new Ville("PUTEAUX",412),
    "COURBEVOIE" => new Ville("COURBEVOIE",413),
    "ASNIERES" => new Ville("ASNIERES",414),
    "GENNEVILLIERS" => new Ville("GENNEVILLIERS",415),
    "VILLENEUVE LA GARENNE" => new Ville("VILLENEUVE LA GARENNE",416),
    "LA DEFENSE" => new Ville("LA DEFENSE",417),
    "BOURG LA REINE" => new Ville("BOURG LA REINE",421),
    "BAGNEUX" => new Ville("BAGNEUX",422),
    "FONTENAY AUX ROSES" => new Ville("FONTENAY AUX ROSES",423),
    "CHATILLON" => new Ville("CHATILLON",424),
    "CLAMART PETIT" => new Ville("CLAMART PETIT",425),
    "CLAMART CENTRE" => new Ville("CLAMART CENTRE",426),
    "MEUDON" => new Ville("MEUDON",427),
    "SEVRES" => new Ville("SEVRES",428),
    "ST CLOUD" => new Ville("ST CLOUD",429),
    "ST DENIS BASILIQUE" => new Ville("ST DENIS BASILIQUE",431),
    "LA COURNEUVE" => new Ville("LA COURNEUVE",432),
    "DRANCY" => new Ville("DRANCY",433),
    "BOBIGNY HOPITAL AVISSEN" => new Ville("BOBIGNY HOPITAL AVISSEN",434),
    "BOBIGNY PREFECTURE" => new Ville("BOBIGNY PREFECTURE",435),
    "ROMAINVILLE" => new Ville("ROMAINVILLE",436),
    "NOISY LE SEC" => new Ville("NOISY LE SEC",437),
    "MONTRUEIL BOISSIERE" => new Ville("MONTRUEIL BOISSIERE",438),
    "CHEVILLY LARUE" => new Ville("CHEVILLY LARUE",440),
    "FONTENAY S/BOIS" => new Ville("FONTENAY S/BOIS",441),
    "NOGENT" => new Ville("NOGENT",442),
    "JOINVILLE" => new Ville("JOINVILLE",443),
    "MAISONS-ALFORT" => new Ville("MAISONS-ALFORT",444),
    "ALFORTVILLE" => new Ville("ALFORTVILLE",445),
    "VITRY" => new Ville("VITRY",446),
    "VILLEJUIF" => new Ville("VILLEJUIF",447),
    "CACHAN" => new Ville("CACHAN",448),
    "L'HAY LES ROSES" => new Ville("L'HAY LES ROSES",449),

    "RUEIL-MALMAISON" => new Ville("RUEIL-MALMAISON",511),
    "NANTERRE" => new Ville("NANTERRE",512),
    "LA GARENNE COLOMBES" => new Ville("LA GARENNE COLOMBES",513),
    "BOIS-COLOMBES" => new Ville("BOIS-COLOMBES",514),
    "ANTONY" => new Ville("ANTONY",521),
    "SCEAUX" => new Ville("SCEAUX",522),
    "CHATENAY MALABRY" => new Ville("CHATENAY MALABRY",523),
    "LE PLESSIS ROBINSON" => new Ville("LE PLESSIS ROBINSON",524),
    "MEUDON LA FORET" => new Ville("MEUDON LA FORET",525),
    "VELIZY" => new Ville("VELIZY",526),
    "CHAVILLE" => new Ville("CHAVILLE",527),
    "MARNE LA COQUETTE - AVRAY" => new Ville("MARNE LA COQUETTE - AVRAY",528),
    "GARCHES VAUCRESSON" => new Ville("GARCHES VAUCRESSON",529),
    "EPINAY - ILE ST DENIS" => new Ville("EPINAY - ILE ST DENIS",531),
    "VILLETANEUSE" => new Ville("VILLETANEUSE",532),
    "PIERREFITTE" => new Ville("PIERREFITTE",533),
    "STAINS" => new Ville("STAINS",534),
    "DUGNY" => new Ville("DUGNY",535),
    "LE BOURGET" => new Ville("LE BOURGET",536),
    "BONDY" => new Ville("BONDY",537),
    "ROSNY" => new Ville("ROSNY",538),
    "PAVILLON S/BOIS" => new Ville("PAVILLON S/BOIS",539),
    "FRESNES" => new Ville("FRESNES",540),
    "LE PERREUX BRY S/MARNE" => new Ville("LE PERREUX BRY S/MARNE",541),
    "CHAMPIGNY" => new Ville("CHAMPIGNY",542),
    "ST MAUR" => new Ville("ST MAUR",543),
    "CRETEIL" => new Ville("CRETEIL",544),
    "BONNEUIL S/MARNE" => new Ville("BONNEUIL S/MARNE",545),
    "CHOISY LE ROI" => new Ville("CHOISY LE ROI",546),
    "THIAIS" => new Ville("THIAIS",547),
    "ORLY" => new Ville("ORLY",548),
    "RUNGIS" => new Ville("RUNGIS",549),

    "LE PECQ" => new Ville("LE PECQ",611),
    "BEZON" => new Ville("BEZON",612),
    "ARGENTEUIL" => new Ville("ARGENTEUIL",613),
    "ENGHIEN" => new Ville("ENGHIEN",614),

    "MASSY PALAISEAU" => new Ville("MASSY PALAISEAU",621),
    "BUC" => new Ville("BUC",622),
    "VERSAILLES" => new Ville("VERSAILLES",623),
    "MARLY LE ROI" => new Ville("MARLY LE ROI",324),

    "ST BRICE" => new Ville("ST BRICE",631),
    "SARCELLES" => new Ville("SARCELLES",632),
    "VILLEPINTE" => new Ville("VILLEPINTE",633),
    "CLICHY SOUS-BOIS" => new Ville("CLICHY SOUS-BOIS",634),
    "GAGNY" => new Ville("GAGNY",635),
    "NOISY-LE-GRAND" => new Ville("NOISY-LE-GRAND",641),
    "ORMESSON" => new Ville("ORMESSON",642),
    "SUCY EN BRIE" => new Ville("SUCY EN BRIE",643),
    "YERRES" => new Ville("YERRES",644),
    "VILLENEUVE LE ROI" => new Ville("VILLENEUVE LE ROI",645),
    "WISSOUS" => new Ville("WISSOUS",646),

    "POISSY" => new Ville("POISSY", 711),
    "ST-GERMAIN EN-LAYE" => new Ville("ST-GERMAIN EN-LAYE",711),
    "PONTOISE" => new Ville("PONTOISE", 712),
    "ST-OUEN L'AUMONE" => new Ville("ST-OUEN L'AUMONE",712),
    "MERY S/O" => new Ville("MERY S/O",713),
    "ST-LEU LA-FORET" => new Ville("ST-LEU LA-FORET",713),
    "VILLEJUST" => new Ville("VILLEJUST",721),
    "MONTHLERY" => new Ville("MONTHLERY",721),
    "GIF/YVETTE" => new Ville("GIF/YVETTE",722),
    "ORSAY" => new Ville("ORSAY",722),
    "MONTIGNY LE BRETONNEUX" => new Ville("MONTIGNY LE BRETONNEUX",723),
    "GUYANCOURT" => new Ville("GUYANCOURT",723),
    "ST CYR L'ECOLE" => new Ville("ST CYR L'ECOLE",724),
    "TRAPPES" => new Ville("TRAPPES",724),
    "ST NOM LA BRETECHE" => new Ville("ST NOM LA BRETECHE",725),
    "MONTSOULT" => new Ville("MONTSOULT",731),
    "ECOUEN" => new Ville("ECOUEN",732),
    "GOUSSAINVILLE" => new Ville("GOUSSAINVILLE",732),
    "ROISSY" => new Ville("ROISSY",733),
    "AEROPORT CDG" => new Ville("700",700),
    "CHELLES" => new Ville("CHELLES",734),
    "CHAMPS SUR MARNE" => new Ville("CHAMPS SUR MARNE",741),
    "BRIE COMPTE ROBERT" => new Ville("BRIE COMPTE ROBERT",742),
    "OZOIR LA FERRIERE" => new Ville("OZOIR LA FERRIERE",742),
    "BRUNOY" => new Ville("BRUNOY",743),
    "RIS ORANGIS" => new Ville("RIS ORANGIS",744),
    "CORBEIL ESSONNE" => new Ville("CORBEIL ESSONNE",744),
    "SAVIGNY SUR ORGE" => new Ville("SAVIGNY SUR ORGE",745),
    "MANTES LA JOLIE" => new Ville("MANTES LA JOLIE",811),
    "MAGNY EN VEXIN" => new Ville("MAGNY EN VEXIN",812),
    "DOURDAN" => new Ville("DOURDAN",821),
    "ETAMPES" => new Ville("ETAMPES",821),
    "ARPAJON" => new Ville("ARPAJON",821),
    "ABLIS" => new Ville("ABLIS",822),
    "RAMBOUILLET" => new Ville("RAMBOUILLET",823),
    "HOUDAN" => new Ville("HOUDAN",824),
    "BEAUMONT SUR OISE" => new Ville("BEAUMONT SUR OISE",831),
    "LUZARCHES" => new Ville("LUZARCHES",831),
    "DAMMARTIN EN GEOLE" => new Ville("DAMMARTIN EN GEOLE",832),
    "LIZY SUR OURCQ" => new Ville("LIZY SUR OURC",832),
    "LA FERTE SOUS JOUARRE" => new Ville("LA FERTE SOUS JOUARRE",841),
    "CRECY LA CHAPELLE" => new Ville("CRECY LA CHAPELLE",841),
    "COULOMMIERS" => new Ville("COULOMMIERS",841),
    "NANGIS" => new Ville("NANGIS",842),
    "ROZAY EN BRIE" => new Ville("ROZAY EN BRIE",842),
    "PROVINS" => new Ville("PROVINS",842),
    "MELUN" => new Ville("MELUN",842),
    "MONTEREAU" => new Ville("MONTEREAU",842),
    "FONTAINEBLEAU" => new Ville("FONTAINEBLEAU",843),
    "LA FERTE ALAIS" => new Ville("LA FERTE ALAIS",844)
));

$mot=$_GET['mot'];
// Retenir uniquement les mots qui contiennent $mot
$suggestions= $villes->getVillesByName($mot);


// Construire le HTML à renvoyer au client
$resultat='';
foreach($suggestions as $suggestion)
{
    $resultat.='<tr><td>'.htmlentities($suggestion->getName()).'</td><td id="numero">'.htmlentities($suggestion->getNumber()).'</td></tr>';

    //$resultat.='<li>'.htmlentities($suggestion->getName()).'</li>';
}
// Envoyer le HTML au client.
echo $resultat;
